#Reading class variables
READING_ATTR_ENV_VAR='READING_ATTR'
READING_ATTR_VAR_NAME='attributes'

#Environment variable name constants
ADDRESS_ENV_VAR='ADDRESS'
PORT_ENV_VAR='PORT'
NUM_OF_SENSORS_ENV_VAR='NUM_OF_SENSORS'
FREQ_ENV_VAR='FREQUENCY'
SENSOR_MODE_ENV_VAR='SENSOR_MODE'

#Default values
DEFAULT_ATTR='{"attributes": ["angle"]}'
DEFAULT_FREQ='10'    #in hz
DEFAULT_ADDRESS='ws://127.0.0.1'
DEFAULT_PORT='5000'
DEFAULT_NUM_OF_SENSORS='4'
DEFAULT_ID_NAME="patient_id"
DEFAULT_READING_EMIT_EVENT="log"
DEFAULT_SENSOR_MODE="MASTER"
